data:
  srcpath: src\
  filepath: data\raw\sobar-72.csv
  processed: data\processed\
  models: models\
  reports: reports\
  plots: dvclive\plots\
  metrics: metrics\
  mod: clf

train_lr:
  solver: liblinear
  C: 0.1   # Regularization parameter for Logistic Regression
  max_iter: 800  # Number of iterations
  penalty: l2
train_clf:
  criterion: gini
  max_depth: none
  splitter: random
train_xgb:
  objective: binary:logistic
  eval_metric: logloss
  max_depth: 500
  learning_rate: 0.001
  n_estimators: 10



