data:
  srcpath: src\
  filepath: data\raw\sobar-72.csv
  processed: data\processed\
  models: models\
  reports: reports\
  plots: dvclive\plots\
  metrics: metrics\
  mod: lr

train_lr:
  solver: liblinear
  C: 0.001 # Regularization parameter for Logistic Regression
  max_iter: 300  # Number of iterations
  penalty: l1
train_clf:
  criterion: log_loss
  max_depth: 10
  splitter: best
train_xgb:
  objective: binary:logistic
  eval_metric: logloss
  max_depth: 500
  learning_rate: 0.001
  n_estimators: 10



